spring.application.name=SeleniumTask
chaintest.storage.service.enabled=false
chaintest.storage.service=azure-blob
chaintest.storage.service.container_name=
chaintest.generator.chainlp.enabled=true
chaintest.generator.chainUp.class-name=com.aventstack.chaintest.generator.ChainLPGenerator
chaintest.generator.chainUp.host.url=http://localhost/
chaintest.generator.chainUp.client.request-timeout-s=30
chaintest.generator.chainUp.client.expect-continue=false
chaintest.generator.chainUp.client.max-retries=3
chaintest.generator.chainUp.persistence=true

# storage

# [azure-blob, aws-s3]

# s3 bucket or azure container name
chaintest.storage.service.container-name=
chaintest.report.dir=chaintest-report
chaintest.report.title=Instagram Login Test Report

## email
chaintest.generator.email.enabled=true
chaintest.generator.email.class-name=com.aventstack.chaintest.generator.ChainTestEmailGenerator
chaintest.generator.email.output-file=target/chaintest/Email.html
chaintest.generator.email.datetime-format=yyyy-MM-dd hh:mm:ss a

## simple
chaintest.generator.simple.enabled=true
chaintest.generator.simple.document-title=chaintest
chaintest.generator.simple.class-name=com.aventstack.chaintest.generator.ChainTestSimpleGenerator
chaintest.generator.simple.output-file=target/chaintest/Index.html
chaintest.generator.simple.offline=false
chaintest.generator.simple.dark-theme=true
chaintest.generator.simple.datetime-format=yyyy-MM-dd hh:mm:ss a
chaintest.generator.simple.js=
chaintest.generator.simple.css=

# generators:
## chainlp

chaintest.generator.chainlp.class-name=com.aventstack.chaintest.generator.ChainLPGenerator
chaintest.generator.chainlp.host.url=http://localhost/
chaintest.generator.chainlp.client.request-timeout-s=30
chaintest.generator.chainlp.client.expect-continue=false
chaintest.generator.chainlp.client.max-retries=3
chaintest.generator.chainlp.persist-embeds=true
